"""Seed data for Hangzhou (杭州) — 26 real POIs with accurate coordinates."""

from scripts.seed_base import check_existing, ensure_tables, get_sync_engine, seed_pois

HANGZHOU_POIS: list[dict] = [
    # ===== 景区/Scenic =====
    {
        "name": "西湖",
        "category": "scenic",
        "lng": 120.1551,
        "lat": 30.2590,
        "rating": 4.9,
        "tags": ["世界遗产", "5A景区", "湖光山色"],
        "description": "杭州西湖，世界文化遗产，十景闻名天下",
        "opening_hours": "全天开放",
        "avg_visit_duration": 180,
        "review_count": 52340,
    },
    {
        "name": "灵隐寺",
        "category": "scenic",
        "lng": 120.1010,
        "lat": 30.2425,
        "rating": 4.7,
        "tags": ["千年古刹", "佛教文化", "飞来峰"],
        "description": "始建于东晋的千年古刹，江南著名佛教圣地",
        "opening_hours": "07:00-18:15",
        "avg_visit_duration": 120,
        "review_count": 28760,
    },
    {
        "name": "千岛湖",
        "category": "scenic",
        "lng": 118.9590,
        "lat": 29.6040,
        "rating": 4.8,
        "tags": ["5A景区", "湖岛风光", "天然氧吧"],
        "description": "天下第一秀水，1078座翠岛散落碧波之上",
        "opening_hours": "08:00-17:00",
        "avg_visit_duration": 360,
        "review_count": 18450,
    },
    {
        "name": "西溪湿地",
        "category": "park",
        "lng": 120.0630,
        "lat": 30.2670,
        "rating": 4.6,
        "tags": ["5A景区", "城市湿地", "生态保护区"],
        "description": "城市湿地公园，水道纵横，芦苇丛生",
        "opening_hours": "08:00-17:30",
        "avg_visit_duration": 180,
        "review_count": 15230,
    },
    {
        "name": "雷峰塔",
        "category": "scenic",
        "lng": 120.1489,
        "lat": 30.2320,
        "rating": 4.5,
        "tags": ["白蛇传说", "西湖十景", "古塔重建"],
        "description": "西湖十景之雷峰夕照所在地，白娘子传说发源地",
        "opening_hours": "08:00-20:30",
        "avg_visit_duration": 60,
        "review_count": 21340,
    },
    {
        "name": "三潭印月",
        "category": "scenic",
        "lng": 120.1470,
        "lat": 30.2430,
        "rating": 4.7,
        "tags": ["西湖十景", "湖中小岛", "一元纸币"],
        "description": "西湖第一胜境，一元纸币背面图案取景地",
        "opening_hours": "08:30-17:00",
        "avg_visit_duration": 60,
        "review_count": 19870,
    },
    {
        "name": "断桥残雪",
        "category": "scenic",
        "lng": 120.1547,
        "lat": 30.2598,
        "rating": 4.6,
        "tags": ["西湖十景", "白蛇传", "冬日雪景"],
        "description": "西湖十景之一，白娘子与许仙相会之处",
        "opening_hours": "全天开放",
        "avg_visit_duration": 30,
        "review_count": 16780,
    },
    {
        "name": "宋城",
        "category": "entertainment",
        "lng": 120.1150,
        "lat": 30.1870,
        "rating": 4.5,
        "tags": ["主题公园", "宋城千古情", "宋代文化"],
        "description": "大型宋文化主题公园，千古情演出震撼人心",
        "opening_hours": "09:00-21:00",
        "avg_visit_duration": 300,
        "review_count": 24560,
    },
    {
        "name": "九溪十八涧",
        "category": "scenic",
        "lng": 120.1180,
        "lat": 30.2100,
        "rating": 4.6,
        "tags": ["溪流山谷", "徒步", "茶园环绕"],
        "description": "溪流潺潺，茶园环绕，杭州天然氧吧",
        "opening_hours": "全天开放",
        "avg_visit_duration": 120,
        "review_count": 8970,
    },
    {
        "name": "龙井村",
        "category": "scenic",
        "lng": 120.1230,
        "lat": 30.2250,
        "rating": 4.7,
        "tags": ["龙井茶", "茶乡", "品茗"],
        "description": "龙井茶原产地，品茗赏景好去处",
        "opening_hours": "全天开放",
        "avg_visit_duration": 120,
        "review_count": 11230,
    },
    {
        "name": "花港观鱼",
        "category": "park",
        "lng": 120.1390,
        "lat": 30.2350,
        "rating": 4.5,
        "tags": ["西湖十景", "园林", "锦鲤"],
        "description": "西湖十景之一，花木繁茂，鱼群嬉戏",
        "opening_hours": "全天开放",
        "avg_visit_duration": 45,
        "review_count": 13450,
    },
    {
        "name": "良渚古城遗址",
        "category": "museum",
        "lng": 120.0150,
        "lat": 30.4150,
        "rating": 4.7,
        "tags": ["世界遗产", "5000年文明", "考古遗址"],
        "description": "5000年中华文明的实证，世界文化遗产",
        "opening_hours": "09:00-17:00",
        "avg_visit_duration": 180,
        "review_count": 9870,
    },
    # ===== 美食/Restaurant =====
    {
        "name": "楼外楼",
        "category": "restaurant",
        "lng": 120.1450,
        "lat": 30.2550,
        "rating": 4.3,
        "tags": ["杭帮菜", "百年老字号", "西湖醋鱼"],
        "description": "创建于1848年的杭帮菜名店，西湖醋鱼闻名遐迩",
        "opening_hours": "11:00-14:00, 17:00-21:00",
        "avg_visit_duration": 90,
        "review_count": 7650,
    },
    {
        "name": "知味观",
        "category": "restaurant",
        "lng": 120.1620,
        "lat": 30.2510,
        "rating": 4.4,
        "tags": ["杭帮菜", "老字号", "小笼包"],
        "description": "百年老字号，杭州传统小吃集大成者",
        "opening_hours": "07:00-21:00",
        "avg_visit_duration": 60,
        "review_count": 9870,
    },
    {
        "name": "外婆家",
        "category": "restaurant",
        "lng": 120.1680,
        "lat": 30.2630,
        "rating": 4.3,
        "tags": ["杭帮菜", "连锁", "性价比高"],
        "description": "杭帮菜连锁品牌，物美价廉，家常风味",
        "opening_hours": "10:30-14:00, 16:30-21:00",
        "avg_visit_duration": 75,
        "review_count": 12340,
    },
    {
        "name": "新白鹿",
        "category": "restaurant",
        "lng": 120.1730,
        "lat": 30.2580,
        "rating": 4.4,
        "tags": ["杭帮菜", "糖醋里脊", "排队"],
        "description": "人气杭帮菜馆，糖醋里脊必点",
        "opening_hours": "10:30-14:00, 16:30-21:00",
        "avg_visit_duration": 75,
        "review_count": 8760,
    },
    # ===== 购物/Shopping =====
    {
        "name": "湖滨银泰in77",
        "category": "shopping",
        "lng": 120.1650,
        "lat": 30.2530,
        "rating": 4.4,
        "tags": ["购物中心", "湖滨", "国际品牌"],
        "description": "紧邻西湖的高端购物中心，集购物餐饮娱乐于一体",
        "opening_hours": "10:00-22:00",
        "avg_visit_duration": 120,
        "review_count": 15670,
    },
    {
        "name": "武林广场",
        "category": "shopping",
        "lng": 120.1690,
        "lat": 30.2720,
        "rating": 4.2,
        "tags": ["商圈", "杭州大厦", "城市地标"],
        "description": "杭州核心商圈，杭州大厦、银泰百货云集",
        "opening_hours": "全天开放",
        "avg_visit_duration": 120,
        "review_count": 8970,
    },
    # ===== 博物馆/Museum =====
    {
        "name": "中国丝绸博物馆",
        "category": "museum",
        "lng": 120.1530,
        "lat": 30.2310,
        "rating": 4.5,
        "tags": ["丝绸文化", "国家级博物馆", "免费"],
        "description": "中国最大的丝绸专业博物馆，展示五千年丝绸文化",
        "opening_hours": "09:00-17:00",
        "avg_visit_duration": 90,
        "review_count": 6780,
    },
    {
        "name": "浙江省博物馆",
        "category": "museum",
        "lng": 120.1430,
        "lat": 30.2530,
        "rating": 4.6,
        "tags": ["省博", "免费", "越王勾践剑"],
        "description": "浙江省最大综合性博物馆，馆藏珍品十万余件",
        "opening_hours": "09:00-17:00",
        "avg_visit_duration": 120,
        "review_count": 11230,
    },
    # ===== 夜生活/Nightlife =====
    {
        "name": "南山路",
        "category": "nightlife",
        "lng": 120.1530,
        "lat": 30.2420,
        "rating": 4.4,
        "tags": ["酒吧街", "艺术", "西湖边"],
        "description": "西湖东岸艺术休闲街区，酒吧画廊林立",
        "opening_hours": "全天开放",
        "avg_visit_duration": 120,
        "review_count": 5670,
    },
    # ===== 休闲/Leisure =====
    {
        "name": "河坊街",
        "category": "leisure",
        "lng": 120.1680,
        "lat": 30.2470,
        "rating": 4.3,
        "tags": ["历史街区", "小吃", "传统工艺"],
        "description": "清河坊历史文化街区，杭州传统市井文化缩影",
        "opening_hours": "全天开放",
        "avg_visit_duration": 90,
        "review_count": 14560,
    },
    {
        "name": "太子湾公园",
        "category": "park",
        "lng": 120.1450,
        "lat": 30.2290,
        "rating": 4.6,
        "tags": ["郁金香", "樱花", "免费"],
        "description": "西湖边最美的公园之一，春季郁金香花海闻名",
        "opening_hours": "全天开放",
        "avg_visit_duration": 60,
        "review_count": 10890,
    },
    {
        "name": "钱塘江大潮观潮点",
        "category": "scenic",
        "lng": 120.1930,
        "lat": 30.2100,
        "rating": 4.5,
        "tags": ["钱塘江", "大潮", "自然奇观"],
        "description": "天下奇观钱塘江大潮最佳观赏点",
        "opening_hours": "全天开放",
        "avg_visit_duration": 60,
        "review_count": 7890,
    },
    {
        "name": "杭州东站",
        "category": "transport",
        "lng": 120.2130,
        "lat": 30.2910,
        "rating": 4.0,
        "tags": ["高铁站", "交通枢纽", "地铁换乘"],
        "description": "杭州主要高铁站，连接全国各大城市",
        "opening_hours": "全天开放",
        "avg_visit_duration": 30,
        "review_count": 23450,
        "extra_data": {"address": "杭州市江干区全福桥路"},
    },
]


def seed_hangzhou() -> None:
    """Seed Hangzhou POIs into the database."""
    engine = get_sync_engine()
    ensure_tables(engine)
    if check_existing(engine, "杭州"):
        return
    seed_pois(engine, "杭州", HANGZHOU_POIS)
    print(f"Hangzhou: {len(HANGZHOU_POIS)} POIs seeded")


if __name__ == "__main__":
    seed_hangzhou()
