"""Seed data for Chengdu (成都) — 27 real POIs with accurate coordinates."""

from scripts.seed_base import check_existing, ensure_tables, get_sync_engine, seed_pois

CHENGDU_POIS: list[dict] = [
    # ===== 景区/Scenic =====
    {
        "name": "大熊猫繁育研究基地",
        "category": "scenic",
        "lng": 104.1480,
        "lat": 30.7320,
        "rating": 4.7,
        "tags": ["5A景区", "大熊猫", "国宝"],
        "description": "全球最大的大熊猫人工繁育基地，近距离观赏国宝",
        "opening_hours": "07:30-18:00",
        "avg_visit_duration": 180,
        "review_count": 45230,
    },
    {
        "name": "都江堰景区",
        "category": "scenic",
        "lng": 103.6180,
        "lat": 30.9980,
        "rating": 4.8,
        "tags": ["世界遗产", "5A景区", "水利工程"],
        "description": "2000多年历史的伟大水利工程，世界文化遗产",
        "opening_hours": "08:00-17:30",
        "avg_visit_duration": 240,
        "review_count": 23450,
    },
    {
        "name": "青城山",
        "category": "scenic",
        "lng": 103.5680,
        "lat": 30.9020,
        "rating": 4.7,
        "tags": ["世界遗产", "道教名山", "幽甲天下"],
        "description": "道教发源地之一，青城天下幽",
        "opening_hours": "08:00-17:00",
        "avg_visit_duration": 300,
        "review_count": 18760,
    },
    {
        "name": "武侯祠博物馆",
        "category": "museum",
        "lng": 104.0440,
        "lat": 30.6410,
        "rating": 4.6,
        "tags": ["4A景区", "三国文化", "诸葛亮"],
        "description": "中国唯一的君臣合祀祠庙，三国文化圣地",
        "opening_hours": "08:00-18:00",
        "avg_visit_duration": 120,
        "review_count": 27890,
    },
    {
        "name": "杜甫草堂",
        "category": "museum",
        "lng": 104.0250,
        "lat": 30.6620,
        "rating": 4.5,
        "tags": ["4A景区", "诗圣故居", "古典园林"],
        "description": "唐代诗圣杜甫流寓成都时的故居，诗歌文化圣地",
        "opening_hours": "08:00-18:00",
        "avg_visit_duration": 90,
        "review_count": 19870,
    },
    {
        "name": "金沙遗址博物馆",
        "category": "museum",
        "lng": 104.0080,
        "lat": 30.6830,
        "rating": 4.6,
        "tags": ["4A景区", "太阳神鸟", "古蜀文明"],
        "description": "3000年前古蜀王国都邑遗址，太阳神鸟图案惊艳世界",
        "opening_hours": "09:00-18:00",
        "avg_visit_duration": 120,
        "review_count": 14560,
    },
    {
        "name": "西岭雪山",
        "category": "scenic",
        "lng": 103.1870,
        "lat": 30.7540,
        "rating": 4.5,
        "tags": ["4A景区", "雪山", "滑雪", "窗含西岭千秋雪"],
        "description": "杜甫诗中窗含西岭千秋雪的取景地，南方滑雪胜地",
        "opening_hours": "08:00-17:00",
        "avg_visit_duration": 360,
        "review_count": 9870,
    },
    {
        "name": "成都欢乐谷",
        "category": "entertainment",
        "lng": 104.0010,
        "lat": 30.7780,
        "rating": 4.4,
        "tags": ["主题公园", "游乐园", "亲子"],
        "description": "大型主题游乐园，老少皆宜的欢乐天地",
        "opening_hours": "09:30-21:30",
        "avg_visit_duration": 360,
        "review_count": 21340,
    },
    {
        "name": "天台山",
        "category": "scenic",
        "lng": 103.2150,
        "lat": 30.3510,
        "rating": 4.4,
        "tags": ["4A景区", "萤火虫", "瀑布"],
        "description": "夏日萤火虫观赏胜地，瀑布群落壮观",
        "opening_hours": "08:00-17:00",
        "avg_visit_duration": 300,
        "review_count": 7650,
    },
    # ===== 美食/Restaurant =====
    {
        "name": "宽窄巷子",
        "category": "leisure",
        "lng": 104.0430,
        "lat": 30.6700,
        "rating": 4.5,
        "tags": ["历史文化街区", "小吃", "茶馆"],
        "description": "成都三大历史文化名城保护街区之一，宽巷子、窄巷子、井巷子",
        "opening_hours": "全天开放",
        "avg_visit_duration": 120,
        "review_count": 38970,
    },
    {
        "name": "锦里古街",
        "category": "leisure",
        "lng": 104.0460,
        "lat": 30.6450,
        "rating": 4.4,
        "tags": ["历史街区", "小吃", "民俗"],
        "description": "武侯祠旁的仿古商业街，体验成都民俗风情",
        "opening_hours": "全天开放",
        "avg_visit_duration": 90,
        "review_count": 32450,
    },
    {
        "name": "陈麻婆豆腐",
        "category": "restaurant",
        "lng": 104.0570,
        "lat": 30.6630,
        "rating": 4.3,
        "tags": ["川菜", "麻婆豆腐", "老字号"],
        "description": "麻婆豆腐创始店，百年老字号，正宗川味",
        "opening_hours": "11:00-14:00, 17:00-21:00",
        "avg_visit_duration": 60,
        "review_count": 8760,
    },
    {
        "name": "小龙坎火锅",
        "category": "restaurant",
        "lng": 104.0750,
        "lat": 30.6580,
        "rating": 4.4,
        "tags": ["火锅", "川味", "麻辣"],
        "description": "正宗成都火锅，麻辣鲜香，牛油锅底醇厚",
        "opening_hours": "11:00-23:00",
        "avg_visit_duration": 120,
        "review_count": 12340,
    },
    {
        "name": "大龙燚火锅",
        "category": "restaurant",
        "lng": 104.0680,
        "lat": 30.6490,
        "rating": 4.5,
        "tags": ["火锅", "网红", "排队"],
        "description": "成都人气火锅，辣味十足，食客络绎不绝",
        "opening_hours": "11:00-02:00",
        "avg_visit_duration": 120,
        "review_count": 10890,
    },
    {
        "name": "蜀九香火锅",
        "category": "restaurant",
        "lng": 104.0350,
        "lat": 30.6550,
        "rating": 4.3,
        "tags": ["火锅", "老成都", "地道"],
        "description": "老成都人喜爱的火锅品牌，地道川味",
        "opening_hours": "11:00-23:00",
        "avg_visit_duration": 120,
        "review_count": 7890,
    },
    {
        "name": "春熙路",
        "category": "shopping",
        "lng": 104.0810,
        "lat": 30.6570,
        "rating": 4.5,
        "tags": ["百年商街", "购物", "美食"],
        "description": "成都最繁华的商业步行街，百年老街汇聚潮流",
        "opening_hours": "全天开放",
        "avg_visit_duration": 120,
        "review_count": 28760,
    },
    {
        "name": "太古里",
        "category": "shopping",
        "lng": 104.0860,
        "lat": 30.6540,
        "rating": 4.6,
        "tags": ["潮流地标", "开放街区", "国际品牌"],
        "description": "成都潮流时尚地标，开放式低密度街区购物中心",
        "opening_hours": "10:00-22:00",
        "avg_visit_duration": 150,
        "review_count": 22340,
    },
    {
        "name": "文殊院",
        "category": "scenic",
        "lng": 104.0620,
        "lat": 30.6790,
        "rating": 4.5,
        "tags": ["佛教寺院", "免费", "素斋"],
        "description": "长江上下游四大禅林之首，香火鼎盛的古寺",
        "opening_hours": "08:00-17:00",
        "avg_visit_duration": 60,
        "review_count": 13450,
    },
    {
        "name": "青羊宫",
        "category": "scenic",
        "lng": 104.0280,
        "lat": 30.6530,
        "rating": 4.4,
        "tags": ["道教宫观", "川西第一道观"],
        "description": "川西第一道观，始建于周朝，历史悠久",
        "opening_hours": "08:00-18:00",
        "avg_visit_duration": 60,
        "review_count": 8970,
    },
    {
        "name": "大慈寺",
        "category": "scenic",
        "lng": 104.0880,
        "lat": 30.6550,
        "rating": 4.4,
        "tags": ["千年古刹", "太古里旁", "免费"],
        "description": "始建于魏晋的千年古刹，与太古里交相辉映",
        "opening_hours": "08:00-17:00",
        "avg_visit_duration": 45,
        "review_count": 7650,
    },
    {
        "name": "人民公园",
        "category": "park",
        "lng": 104.0550,
        "lat": 30.6620,
        "rating": 4.5,
        "tags": ["百年公园", "茶馆", "掏耳朵"],
        "description": "成都人的休闲客厅，喝茶掏耳朵体验地道慢生活",
        "opening_hours": "全天开放",
        "avg_visit_duration": 90,
        "review_count": 16780,
    },
    {
        "name": "成都博物馆",
        "category": "museum",
        "lng": 104.0610,
        "lat": 30.6590,
        "rating": 4.6,
        "tags": ["综合性博物馆", "免费", "天府文化"],
        "description": "成都市最大的综合性博物馆，展示天府文化",
        "opening_hours": "09:00-20:30",
        "avg_visit_duration": 120,
        "review_count": 11230,
    },
    {
        "name": "东郊记忆",
        "category": "entertainment",
        "lng": 104.1260,
        "lat": 30.6580,
        "rating": 4.3,
        "tags": ["文创园区", "工业遗存", "音乐"],
        "description": "由原红光电子管厂改建的文创产业园区",
        "opening_hours": "全天开放",
        "avg_visit_duration": 120,
        "review_count": 9870,
    },
    {
        "name": "望江楼公园",
        "category": "park",
        "lng": 104.0990,
        "lat": 30.6380,
        "rating": 4.4,
        "tags": ["薛涛遗址", "竹子", "锦江边"],
        "description": "纪念唐代女诗人薛涛的古典园林，竹子品种繁多",
        "opening_hours": "全天开放",
        "avg_visit_duration": 60,
        "review_count": 6780,
    },
    {
        "name": "九眼桥",
        "category": "nightlife",
        "lng": 104.0920,
        "lat": 30.6450,
        "rating": 4.3,
        "tags": ["酒吧街", "夜生活", "锦江边"],
        "description": "成都夜生活地标，酒吧一条街热闹非凡",
        "opening_hours": "全天开放",
        "avg_visit_duration": 120,
        "review_count": 11230,
    },
    {
        "name": "成都东站",
        "category": "transport",
        "lng": 104.1380,
        "lat": 30.6320,
        "rating": 4.0,
        "tags": ["高铁站", "交通枢纽", "地铁换乘"],
        "description": "成都主要高铁站之一，连接成渝及全国各地",
        "opening_hours": "全天开放",
        "avg_visit_duration": 30,
        "review_count": 25670,
        "extra_data": {"address": "成都市成华区邛崃山路"},
    },
    {
        "name": "四川博物院",
        "category": "museum",
        "lng": 104.0230,
        "lat": 30.6630,
        "rating": 4.5,
        "tags": ["省级博物馆", "免费", "张大千"],
        "description": "西南地区最大的综合性博物馆，藏有张大千真迹",
        "opening_hours": "09:00-17:00",
        "avg_visit_duration": 120,
        "review_count": 8970,
    },
]


def seed_chengdu() -> None:
    """Seed Chengdu POIs into the database."""
    engine = get_sync_engine()
    ensure_tables(engine)
    if check_existing(engine, "成都"):
        return
    seed_pois(engine, "成都", CHENGDU_POIS)
    print(f"Chengdu: {len(CHENGDU_POIS)} POIs seeded")


if __name__ == "__main__":
    seed_chengdu()
